import { Inter } from 'next/font/google'
import './globals.css'
import AppProvider from '@/context/appContext'
import {notFound} from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })
const locales = ['en', 'zh'];
 

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function LocaleLayout({children, params: {locale}}) {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale)) notFound();
  return (
    <html lang={locale}>
      <AppProvider>
      <body className={inter.className}>{children}</body>
      </AppProvider>
      
    </html>
  )
}


 
// Can be imported from a shared config


 
 
